### ISSUE TITLE
Does it scale?

### ISSUE THREAD

**Issue by 5chdn** [lexansoft/etherid.org#3]
Excuse me for all the tickets i'm opening, but I like the etherid and think about adding services on top.

My Follow-up question would be now, do you see any potential for performance improvements? Does etherid scale, lets say how does it handle millions of registered domains? I'm not sure if this might be also an ethereum issue. I have the feeling with 10k domains registered it's already no fun to query the blockchain.

**Comment by lexansoft** [comment]
It is organized as a hash, so the access to a particular domain is instant (it does not go through the whole list, but directly access the records) That means, no matter how many domains are registered, the access time will be the same.

The only timely operation is to list all the registered domains. The reason is access to the EVM memory is slow. 

If you compare it to DNS, it is sort of the same. You can access any record fast, but if you want to list all the registered domains, it is a different story.

Someone can mirror the EtherID storage into some relational DB, to query fast. But then some synchronization background process should be implemented. It is all doable.

But the main usage is to control your domain, not to track what ID's other people change.

**Comment by 5chdn** [comment]
Awesome thanks. I have to admit this is my favourite dapp right now, will keep a tab on it.

**Comment by lexansoft** [comment]
;) tx

Alexandre Naverniouk
